from decouple import config

AFRICAS_TALKING_API_KEY = config(
    "AFRICAS_TALKING_API_KEY"
)
AFRICASTALKING_USERNAME = config("AFRICASTALKING_USERNAME")
AFRICASTALKING_SENDER_ID = config("AFRICASTALKING_SENDER_ID")
