# Generated by Django 4.1 on 2022-08-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connections',
            options={},
        ),
        migrations.AlterField(
            model_name='connections',
            name='points',
            field=models.IntegerField(),
        ),
    ]
