# Generated by Django 4.1 on 2022-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connections_options_alter_connections_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
