# Generated by Django 4.1 on 2022-08-05 05:09

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('ld_number', models.CharField(max_length=10, unique=True)),
                ('date_listened', models.DateField()),
                ('podcast_name', models.CharField(max_length=255)),
                ('podcast_link', models.CharField(max_length=500, unique=True)),
                ('podcast_category', models.CharField(choices=[('Finance', 'Finance'), ('Legal', 'Legal'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Social Media', 'Social Media'), ('Design', 'Design'), ('Product', 'Product'), ('Leadership', 'Leadership'), ('Mindset', 'Mindset'), ('Communication & Story Telling', 'Communication & Story Telling'), ('Culture', 'Culture'), ('OKRS', 'OKRS'), ('General', 'General')], default='General', max_length=500)),
                ('podcast_group', models.CharField(max_length=255)),
                ('podcast_notes', models.CharField(max_length=1024)),
                ('points', models.IntegerField(max_length=100)),
            ],
            options={
                'ordering': [builtins.id],
            },
        ),
    ]
