# Generated by Django 4.1 on 2022-08-05 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('ld_number', models.CharField(max_length=10, unique=True)),
                ('date_listened', models.DateField()),
                ('podcast_name', models.CharField(max_length=255)),
                ('podcast_link', models.CharField(max_length=500, unique=True)),
                ('podcast_category', models.CharField(choices=[('Finance', 'Finance'), ('Legal', 'Legal'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Social Media', 'Social Media'), ('Design', 'Design'), ('Product', 'Product'), ('Leadership', 'Leadership'), ('Mindset', 'Mindset'), ('Communication & Story Telling', 'Communication & Story Telling'), ('Culture', 'Culture'), ('OKRS', 'OKRS'), ('General', 'General')], default='General', max_length=500)),
                ('podcast_group', models.CharField(max_length=255)),
                ('podcast_notes', models.CharField(max_length=1024)),
                ('points', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
