# Generated by Django 4.1 on 2022-08-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcasts',
            options={},
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='points',
            field=models.IntegerField(),
        ),
    ]
