# Generated by Django 4.1 on 2022-08-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_podcasts_options_alter_podcasts_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
