# Generated by Django 4.0 on 2022-08-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_podcasts_ld_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcasts',
            name='owner',
        ),
    ]
